services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   working_dir: /app
  #   command: uv run fastapi dev main.py --host 0.0.0.0 --port 8000
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - UV_PROJECT_ENVIRONMENT=/app/.venv
  #   volumes:
  #     - ./backend:/app
  #     - venv:/app/.venv
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gloorp
      POSTGRES_DB: food_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  venv: