"""Place review support

Revision ID: 255188568530
Revises: 5b7defc0c06f
Create Date: 2026-04-08 17:45:12.232882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '255188568530'
down_revision: Union[str, Sequence[str], None] = '5b7defc0c06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('food_place_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'food_places', ['food_place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'food_place_id')
    # ### end Alembic commands ###
