"""Image url fields

Revision ID: 5b7defc0c06f
Revises: 539f014d1f29
Create Date: 2026-04-08 10:44:49.857207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b7defc0c06f'
down_revision: Union[str, Sequence[str], None] = '539f014d1f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_places_name'), 'food_places', ['name'], unique=True)
    op.drop_index(op.f('ix_votes_created_at'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.add_column('food_items', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('food_items', sa.Column('food_place_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'food_items', 'food_places', ['food_place_id'], ['id'])
    op.add_column('users', sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_constraint(None, 'food_items', type_='foreignkey')
    op.drop_column('food_items', 'food_place_id')
    op.drop_column('food_items', 'image_url')
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reporter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('review_id IS NOT NULL AND comment_id IS NULL OR review_id IS NULL AND comment_id IS NOT NULL', name=op.f('ck_reports_single_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('reports_comment_id_fkey')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('reports_reporter_id_fkey')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('reports_review_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey')),
    sa.UniqueConstraint('reporter_id', 'comment_id', name=op.f('uq_reports_user_comment'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('reporter_id', 'review_id', name=op.f('uq_reports_user_review'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_upvote', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('review_id IS NOT NULL AND comment_id IS NULL OR review_id IS NULL AND comment_id IS NOT NULL', name=op.f('ck_votes_single_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('votes_comment_id_fkey')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('votes_review_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('votes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('votes_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name=op.f('uq_votes_user_comment'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'review_id', name=op.f('uq_votes_user_review'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_votes_created_at'), 'votes', ['created_at'], unique=False)
    op.drop_index(op.f('ix_food_places_name'), table_name='food_places')
    op.drop_table('food_places')
    # ### end Alembic commands ###
