"""Add missing created_at to reviews

Revision ID: c2e716c341d0
Revises: 1bab4bb32f4d
Create Date: 2026-04-08 21:21:55.000512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2e716c341d0'
down_revision: Union[str, Sequence[str], None] = '1bab4bb32f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_column('reviews', 'created_at')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
