"""Fixed foreign key errors

Revision ID: f165d2456e30
Revises: 5b1ab093c32e
Create Date: 2026-04-12 15:24:49.346993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f165d2456e30'
down_revision: Union[str, Sequence[str], None] = '5b1ab093c32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_food_place_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'food_place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('food_place_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reviews_food_place_id_fkey'), 'reviews', 'food_places', ['food_place_id'], ['id'])
    # ### end Alembic commands ###
