"""Added average rating field in items

Revision ID: f17f5a60b623
Revises: ed53d36ae13e
Create Date: 2026-04-12 15:17:32.659178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f17f5a60b623'
down_revision: Union[str, Sequence[str], None] = 'ed53d36ae13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('average_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'average_rating')
    # ### end Alembic commands ###
